name: Feature Request
description: Suggest an amazing new feature for kbackup
title: "[Feature]: "
labels: [ "enhancement" ]
assignees:
- Kyuubang
body:
- type: markdown
  attributes:
    value: |
      ## 🚀 Feature Request
      Thanks for taking the time to suggest a new feature! Your ideas help make kbackup better for everyone.

- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com
  validations:
    required: false

- type: textarea
  id: problem
  attributes:
    label: Problem Statement
    description: What problem are you trying to solve? What's the pain point?
    placeholder: I'm always frustrated when...
  validations:
    required: true

- type: textarea
  id: solution
  attributes:
    label: Proposed Solution
    description: How would you like this feature to work? Be as detailed as possible.
    placeholder: I would like kbackup to...
  validations:
    required: true

- type: textarea
  id: alternatives
  attributes:
    label: Alternatives Considered
    description: Have you considered any alternative solutions or workarounds?
    placeholder: I've tried... but it doesn't work because...
  validations:
    required: false

- type: dropdown
  id: feature-type
  attributes:
    label: Feature Type
    description: What type of feature is this?
    options:
    - New backup option/filter
    - Performance improvement
    - CLI enhancement
    - Output format
    - Integration with other tools
    - Other
  validations:
    required: true

- type: dropdown
  id: priority
  attributes:
    label: Priority
    description: How important is this feature to you?
    options:
    - Nice to have
    - Would improve my workflow
    - Critical for my use case
  validations:
    required: false

- type: textarea
  id: use-case
  attributes:
    label: Use Case
    description: Describe your specific use case. Who would benefit from this?
    placeholder: |
      Example: When backing up production clusters...
      This would help teams that...
  validations:
    required: false

- type: textarea
  id: additional-context
  attributes:
    label: Additional Context
    description: Add any other context, screenshots, examples, or mockups about the feature request here.
    placeholder: You can attach images by dragging and dropping them here.
  validations:
    required: false

- type: checkboxes
  id: contribution
  attributes:
    label: Contribution
    description: Would you be willing to contribute to this feature?
    options:
    - label: I'm willing to submit a PR for this feature
      required: false
    - label: I can help test this feature
      required: false

- type: checkboxes
  id: checklist
  attributes:
    label: Pre-submission Checklist
    description: Please confirm the following before submitting
    options:
    - label: I have searched existing issues to ensure this is not a duplicate
      required: true
    - label: I have checked the documentation and this feature doesn't already exist
      required: true
